name: conlang
services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: conlang
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - './docker/app/php.ini:/usr/local/etc/php/php.ini'
        networks:
            - LaraVueVite
        depends_on:
            - pgsql
    pgsql:
        image: 'postgres:14'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'nova_site-pgsql:/var/lib/postgresql/data'
        networks:
            - LaraVueVite
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - '${APP_PORT:-80}:80'
            - '443:443'
        volumes:
            - '.:/var/www/html'
            - './docker/nginx:/etc/nginx/conf.d'
            - './docker/nginx/ssl:/etc/nginx/ssl'
            - '/etc/letsencrypt:/etc/letsencrypt'
        networks:
            - LaraVueVite
        depends_on:
            - app
        restart: unless-stopped
networks:
    LaraVueVite:
        driver: bridge
volumes:
    nova_site-pgsql:
        driver: local
